export const ERRORS = {
  UNSUPPORTED_TYPE: "UNSUPPORTED_TYPE",
  UNRECOGNIZED_ENUM: "UNRECOGNIZED_ENUM",
  NO_OR_WRONG_VALUE: "NO_OR_WRONG_VALUE",
  NO_SPACE_ALLOWED: "NO_SPACE_ALLOWED",
  MALFORMED_INPUT: "MALFORMED_INPUT",
  ZERO_LENGTH_ENTRY: "ZERO_LENGTH_ENTRY",
  ASSIGNMENT_REQUIRED: "ASSIGNMENT_REQUIRED",
} as const;

export const LOGS = {
  IGNORING_CONFLICT: "Ignoring conflict",
  HASH_DEFINED_TWICE: "Hash defined twice",
  keyDefinedTwice: (key: string) => `Key '${key}' defined twice`,
} as const;
