name: Push

on:
  push:
    tags:
      - "experiment/**/**/**"
    # paths:
    #   - apps/**
    #   - packages/**
    #   - .github/workflows/push.yml
    #   - .github/workflows/build-test-push.wfc.yml
    #   - .github/workflows/web.build.wfc.yml
    #   - .github/workflows/android.build.wfc.yml
    #   - .github/workflows/web-server-endpoints.test.wfc.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  android-build:
    uses: ./.github/workflows/android.build.wfc.yml
    secrets: inherit
    # permissions:
    #   contents: write

  tauri-build:
    uses: ./.github/workflows/tauri.build.wfc.yml
    secrets: inherit
    # permissions:
    #   contents: write
